#!/usr/bin/env python3
from utils.blocks import *
from utils.objects import mainExecutable, apiHandler

if __name__ == "__main__":
    content = mainExecutable.Generator().initializer()
    if not content:
        print ("No se pudo generar la imágen.")
    else:
        open("output.png", "wb").write(content["ListAux"][-1].content)